config/routes.php
<?php

/**
 * Routes configuration.
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * It's loaded within the context of `Application::routes()` method which
 * receives a `RouteBuilder` instance `$routes` as method argument.
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */
use Cake\Routing\Route\DashedRoute;
use Cake\Routing\RouteBuilder;

/*
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 */
/** @var \Cake\Routing\RouteBuilder $routes */
$routes->setRouteClass(DashedRoute::class);

$routes->scope('/', function (RouteBuilder $builder)
{
    /*
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, templates/Pages/home.php)...
     */
    //$builder->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);
    $builder->connect('/', ['controller' => 'Hosts', 'action' => 'index']);

    /*
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $builder->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);
    
    /**
     * Allow JSON data views
     */
    $builder->addExtensions(['json']);

    /*
     * Connect catchall routes for all controllers.
     *
     * The `fallbacks` method is a shortcut for
     *
     * ```
     * $builder->connect('/:controller', ['action' => 'index']);
     * $builder->connect('/:controller/:action/*', []);
     * ```
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $builder->fallbacks();
});

/*
 * If you need a different set of middleware or none at all,
 * open new scope and define routes there.
 *
 * ```
 * $routes->scope('/api', function (RouteBuilder $builder) {
 *     // No $builder->applyMiddleware() here.
 *     // Connect API actions here.
 * });
 * ```
 */

src/Model/Entity/Host.php
<?php

declare(strict_types=1);

namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * Host Entity
 *
 * @property int $id
 * @property int $user_id
 * @property string $name
 * @property string|null $description
 * @property string $domain
 * @property \Cake\I18n\FrozenTime|null $created
 * @property \Cake\I18n\FrozenTime|null $modified
 *
 * @property Service[] $services
 * @property User $user
 */
class Host extends Entity
{

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        'user_id' => false, // Do not allow transfer of owner
        'name' => true,
        'description' => true,
        'domain' => true,
        'created' => true,
        'modified' => true,
        'services' => true,
        'user' => false,
    ];

}

src/Model/Entity/Service.php
<?php

declare(strict_types=1);

namespace App\Model\Entity;

use Cake\ORM\Entity;
use App\Model\Table\ServicesTable;

/**
 * Service Entity
 *
 * @property int $id
 * @property int $host_id
 * @property string $name
 * @property string $type
 * @property string $target
 * @property int|null $rate
 * @property \Cake\I18n\FrozenTime|null $created
 * @property \Cake\I18n\FrozenTime|null $modified
 * @property string $typeLabel
 * @property float $uptimeFromTotal
 * @property string $intervalFormat
 *
 * @property \App\Model\Entity\Host $host
 * @property \App\Model\Entity\Ping[] $pings
 */
class Service extends Entity
{

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        'host_id' => true,
        'name' => true,
        'type' => true,
        'target' => true,
        'rate' => true,
        'created' => true,
        'modified' => true,
        'host' => true,
        'pings' => true,
    ];

    /**
     * Get pretty name of type
     * 
     * @return string
     */
    protected function _getTypeLabel()
    {
        $type = $this->type;
        return ServicesTable::TYPES_LABELS[$type];
    }
    
    /**
     * Get uptime ratio from downtime and uptime fields
     * 
     * @return real
     */
    protected function _getUptimeFromTotal()
    {
        if (is_null($this->time_total) || is_null($this->uptime))
        {
            return null;
        }
        
        $total = floatval($this->time_total);
        $up = floatval($this->uptime);
        
        if ($total < 1)
        {
            return null;
        }
        
        $ratio = $up / ($total);
        
        return $ratio;
    }
    
    /**
     * Get human-readable format of rate
     * 
     * \DateInterval is not helpful here.
     * 
     * @return string
     */
    protected function _getIntervalFormat()
    {
        if (is_null($this->rate))
        {
            return 'Never';
        }
        
        if ($this->rate < 60)
        {
            return "{$this->rate} minutes";
        }
        elseif ($this->rate < 1440)
        {
            $hours = abs($this->rate / 60);
            return "{$hours} hour(s)";
        }
        else
        {
            $days = abs($this->rate / 60 / 24);
            return "{$days} day(s)";
        }
    }
}

src/Model/Table/HostsTable.php
<?php

declare(strict_types=1);

namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;
use Cake\Event\EventInterface;
use ArrayObject;

/**
 * Hosts Model
 *
 * @property ServicesTable&\Cake\ORM\Association\HasMany $Services
 * @property UsersTable&\Cake\ORM\Association\BelongsTo $Users
 *
 * @method \App\Model\Entity\Host newEmptyEntity()
 * @method \App\Model\Entity\Host newEntity(array $data, array $options = [])
 * @method \App\Model\Entity\Host[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Host get($primaryKey, $options = [])
 * @method \App\Model\Entity\Host findOrCreate($search, ?callable $callback = null, $options = [])
 * @method \App\Model\Entity\Host patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Host[] patchEntities(iterable $entities, array $data, array $options = [])
 * @method \App\Model\Entity\Host|false save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Host saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Host[]|\Cake\Datasource\ResultSetInterface|false saveMany(iterable $entities, $options = [])
 * @method \App\Model\Entity\Host[]|\Cake\Datasource\ResultSetInterface saveManyOrFail(iterable $entities, $options = [])
 * @method \App\Model\Entity\Host[]|\Cake\Datasource\ResultSetInterface|false deleteMany(iterable $entities, $options = [])
 * @method \App\Model\Entity\Host[]|\Cake\Datasource\ResultSetInterface deleteManyOrFail(iterable $entities, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class HostsTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config): void
    {
        parent::initialize($config);

        $this->setTable('hosts');
        $this->setDisplayField('name');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->hasMany('Services')
                ->setDependent(true); // Cascading delete
        $this->belongsTo('Users');
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator): Validator
    {
        $validator
                ->integer('id')
                ->allowEmptyString('id', null, 'create');

        $validator
                ->integer('user_id')
                ->notEmptyString('user_id');

        $validator
                ->scalar('name')
                ->maxLength('name', 100)
                ->requirePresence('name', 'create')
                ->notEmptyString('name');

        $validator
                ->scalar('description')
                ->allowEmptyString('description');

        $validator
                ->scalar('domain')
                ->maxLength('domain', 255)
                ->requirePresence('domain', 'create')
                ->notEmptyString('domain');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules): RulesChecker
    {
        $rules->add($rules->existsIn(['user_id'], 'Users'), ['errorField' => 'user_id']);

        return $rules;
    }

    /**
     * Marshal data before entity patch
     * 
     * @param EventInterface $event
     * @param ArrayObject $data
     * @param ArrayObject $options
     */
    public function beforeMarshal(EventInterface $event, ArrayObject $data, ArrayObject $options)
    {
        if (isset($data['description']))
        {
            $data['description'] = trim($data['description']);
            if (strlen($data['description']) == 0)
            {
                $data['description'] = null;
            }
        }
    }

}

src/Controller/HostsController.php
<?php

declare(strict_types=1);

namespace App\Controller;

/**
 * Hosts Controller
 *
 * @property \App\Model\Table\HostsTable $Hosts
 * @method \App\Model\Entity\Host[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class HostsController extends AppController
{

    /**
     * Index method
     *
     * @return \Cake\Http\Response|null|void Renders view
     */
    public function index()
    {
        $this->Authorization->skipAuthorization();
        
        $query = $this->Hosts->find();
        
        $query = $this->Authorization->applyScope($query, 'index');
        
        $hosts = $this->paginate($query);

        $this->set(compact('hosts'));
    }

    /**
     * View method
     *
     * @param string|null $id Host id.
     * @return \Cake\Http\Response|null|void Renders view
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $host = $this->Hosts->get($id, [
            'contain' => [
                'Services' => function ($q)
                {
                    return $q->find('upAndDowntime');
                },
                'Services.LastPings',
            ]
        ]);

        $this->Authorization->authorize($host, 'view');

        $this->set(compact('host'));
    }

    /**
     * Edit and add method
     *
     * @param string|null $id Host id.
     * @return \Cake\Http\Response|null|void Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function edit($id = null)
    {
        if (is_null($id))
        {
            $host = $this->Hosts->newEmptyEntity();

            $this->Authorization->authorize($host, 'create');
        }
        else
        {
            $host = $this->Hosts->get($id);
            $this->Authorization->authorize($host, 'update');
        }

        if ($this->request->is(['patch', 'post', 'put']))
        {
            $host->user_id = $this->request->getAttribute('identity')->getIdentifier();
            $host = $this->Hosts->patchEntity($host, $this->request->getData());
            
            if ($this->Hosts->save($host))
            {
                $this->Flash->success(__('The host has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The host could not be saved. Please, try again.'));
        }
        $this->set(compact('host'));
    }

    /**
     * Delete method
     *
     * @param string|null $id Host id.
     * @return \Cake\Http\Response|null|void Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $host = $this->Hosts->get($id);
        
        $this->Authorization->authorize($host, 'delete');
        
        if ($this->Hosts->delete($host))
        {
            $this->Flash->success(__('The host has been deleted.'));
        }
        else
        {
            $this->Flash->error(__('The host could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'index']);
    }

}

templates/Hosts/edit.php
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Host $host
 */
?>

<div class="form content">
    <?= $this->Form->create($host) ?>
    <fieldset>
        <legend><?= $host->isNew() ? 'Add Host' : 'Edit Host' ?></legend>
        <?php
        echo $this->Form->control('name');
        echo $this->Form->control('description');
        echo $this->Form->control('domain');
        ?>
    </fieldset>
    <div class="btn-group" role="group">
        <?= $this->Form->button('Submit') ?>
        <?= $this->Html->link('Cancel', ['action' => 'index'], ['class' => 'btn btn-primary']) ?>
    </div>
    <?= $this->Form->end() ?>
</div>

templates/Hosts/index.php
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Host[]|\Cake\Collection\CollectionInterface $hosts
 */
?>
<div class="content">
    
    <?= $this->Html->link(__('New Host'), ['action' => 'edit'], ['class' => 'btn btn-primary float-right']) ?>
    <h3><?= __('Hosts') ?></h3>
    
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th><?= $this->Paginator->sort('name') ?></th>
                    <th><?= $this->Paginator->sort('domain') ?></th>
                    <th><?= $this->Paginator->sort('created') ?></th>
                    <th class="actions"></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($hosts as $host): ?>
                    <tr>
                        <td><?= $this->Html->link($host->name, ['action' => 'view', $host->id]) ?></td>
                        <td><?= h($host->domain) ?></td>
                        <td><?= h($host->created) ?></td>
                        <td class="actions">
                            <?= $this->Html->link(__('Edit'), ['action' => 'edit', $host->id]) ?>
                            <?= $this->Form->postLink(__('Delete'), ['action' => 'delete', $host->id], ['confirm' => __('Are you sure you want to delete "{0}"?', $host->name)]) ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    
    <?= $this->element('basics/pagination_panel') ?>

</div>

templates/Hosts/view.php
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Host $host
 */
$this->Html->script('services', ['block' => true]);
?>
<div class="content">
    <h3>Host: <?= h($host->name) ?></h3>
    <table class="table table-sm">
        <tr>
            <th>Name</th>
            <td><?= h($host->name) ?></td>
        </tr>
        <tr>
            <th>Domain</th>
            <td><?= h($host->domain) ?></td>
        </tr>
        <tr>
            <th>Created</th>
            <td><?= h($host->created) ?></td>
        </tr>
        <tr>
            <th>Description</th>
            <td>
                <blockquote>
                    <?= $this->Text->autoParagraph(h($host->description)); ?>
                </blockquote>
            </td>
        </tr>
    </table>

    <div class="related">

        <?= $this->Html->link('New Service', ['controller' => 'Services', 'action' => 'edit', '?' => ['host_id' => $host->id]], ['class' => 'btn btn-primary float-right']) ?>
        <h4>Services</h4>

        <?php if (!empty($host->services)) : ?>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Last status / Up-time</th>
                            <th>Type</th>
                            <th>Target</th>
                            <th>Interval</th>
                            <th class="actions"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($host->services as $service) : ?>
                            <tr>
                                <td><?= $this->Html->link($service->name, ['controller' => 'Services', 'action' => 'view', $service->id]) ?></td>
                                <td>
                                    <?= $this->element('service/status', compact('service')) ?>
                                    <?= $this->element('service/uptime', compact('service')) ?><br>
                                    <?php if ($service->has('last_ping')): ?>
                                        <span class="last-ping-date">
                                            Last: <?= $service->last_ping->finished ?>
                                        </span>
                                    <?php endif; ?>
                                </td>
                                <td><?= h($service->typeLabel) ?></td>
                                <td><?= h($service->target) ?></td>
                                <td><?= $service->interval_format ?></td>
                                <td class="actions">
                                    <?=
                                    $this->Form->button('Run', [
                                        'type' => 'button',
                                        'class' => 'btn btn-secondary test-service',
                                        'data-id' => $service->id
                                    ])
                                    ?>
                                    <?= $this->Html->link('Edit', ['controller' => 'Services', 'action' => 'edit', $service->id]) ?>
                                    <?= $this->Form->postLink('Delete', ['controller' => 'Services', 'action' => 'delete', $service->id], ['confirm' => __('Are you sure you want to delete "{0}"?', $service->name)]) ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        <?php endif; ?>
    </div>
</div>

<script>
    $(document).ready(function () {

        $("button.test-service").service();
    });
</script>